if(!window.assBar) {
    window.assBar = {};
}
window.assBar.projectData = {
    name: 'WikiProject India',
    inputTemplates: ['WP India', 'WikiProject India', 'WPINDIA', 'WPIndia'],
    outputTemplate: 'WikiProject India',
    subProjects: [
            'andaman',
            'andhra',
            'arunachal',
            'assam',
            'bihar',
            'chandigarh',
            'chhattisgarh',
            'dadra',
            'daman',
            'delhi',
            'goa',
            'gujarat',
            'haryana',
            'himachal',
            'jandk',
            'jharkhand',
            'karnataka',
            'kerala',
            'lakshya',
            'madhya',
            'maharashtra',
            'manipur',
            'meghalaya',
            'mizoram',
            'nagaland',
            'orissa',
            'puducherry',
            'punjab',
            'rajasthan',
            'sikkim',
            'tamilnadu',
            'tripura',
            'uttar',
            'uttarakand',
            'bengal',
            'mumbai',
            'mangalore',
            'chennai',
            'hyderabad',
            'geography',
            'states',
            'districts',
            'cities',
            'maps',
            'history',
            'literature',
            'politics',
            'language',
            'cinema',
            'music',
            'television',
            'education',
            'tamil',
            'gender',
            'railways',
            'transport',
            'protected-areas'
        ],
    actionNeeded: [
        'orphan',
        'needs-infobox',
        'map-needed',
        'image-needed',
        'attention',
        'pre'
    ],
    importanceOptions: [
        'top', 'high', 'mid', 'low', 'unassessed'
    ],
    classOptions: [
        'stub', 'start', 'c', 'b', 'ga', 'a', 'fa', 'list', 'unassessed'
    ]
};
